const ALBUMS=["A Sede","O Campo","A Mesa","Gente da casa"];
const KEY="paiol.album.v2";
const DEMO={started:false,farm:"Fazenda Santa Luzia",place:"Sede · cerrado",family:"Alcântara",volume:"volume I",cover:"https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80",farmPhoto:"https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=1600&q=80",people:[],events:[],stories:[],photos:[]};
function emptyHouse(){return {started:true,farm:"",place:"",family:"",volume:"volume I",cover:"",farmPhoto:"",people:[],events:[],stories:[],photos:[]};}
function load(){try{const raw=localStorage.getItem(KEY);if(!raw)return Object.assign(emptyHouse(),JSON.parse(JSON.stringify(DEMO)));return Object.assign(emptyHouse(),JSON.parse(raw));}catch(e){return Object.assign(emptyHouse(),JSON.parse(JSON.stringify(DEMO)));}}
function save(state){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){toast("Memória cheia. Baixa o backup e apaga uma foto.");}}
let state=load();
function $(sel){return document.querySelector(sel);}
function uid(){return "p"+Date.now().toString(36)+Math.random().toString(36).slice(2,6);}
function toast(msg){var el=document.getElementById("toast");if(!el){el=document.createElement("div");el.id="toast";el.style.cssText="position:fixed;bottom:1.2rem;left:50%;transform:translateX(-50%);background:#2b2218;color:#f3eee4;padding:.7rem 1rem;border-radius:999px;z-index:80;font-size:.9rem;max-width:90vw;text-align:center";document.body.appendChild(el);}el.textContent=msg;el.style.display="block";clearTimeout(toast._t);toast._t=setTimeout(function(){el.style.display="none";},2800);}
function readFile(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(r.result);};r.onerror=function(){reject(new Error("read"));};r.readAsDataURL(file);});}
function compressFile(file){return readFile(file).then(function(raw){return new Promise(function(resolve){var image=new Image();var done=false;var finish=function(val){if(done)return;done=true;resolve(val);};var t=setTimeout(function(){finish(raw);},5000);image.onload=function(){clearTimeout(t);try{var max=1400;var scale=Math.min(1,max/Math.max(image.width,image.height));var canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);finish(canvas.toDataURL("image/jpeg",0.72));}catch(e){finish(raw);}};image.onerror=function(){clearTimeout(t);finish(raw);};image.src=raw;});});}
function go(view){document.querySelectorAll(".view").forEach(function(v){v.classList.toggle("active",v.id===view);});document.querySelectorAll(".nav button").forEach(function(b){b.classList.toggle("active",b.dataset.view===view);});window.scrollTo({top:0,behavior:"smooth"});}
function renderHouse(){if(!$("#cover-kicker"))return;$("#cover-kicker").textContent=[state.farm||"A fazenda",state.volume||"volume I"].join(" · ");$("#cover-img").src=state.cover||DEMO.cover;$("#farm-img").src=state.farmPhoto||state.cover||DEMO.farmPhoto;$("#farm-title").textContent=state.farm||"Sua fazenda";$("#farm-place").textContent=state.place||"Município · sede";$("#farm-note").textContent=state.started?(state.family?"Família "+state.family+".":"A casa já está no seu nome."):"Isto ainda é o exemplo.";$("#cover-lede").textContent=state.started&&state.farm?("Álbum da "+state.farm+(state.family?", família "+state.family:"")+"."):"Paiol é o álbum da casa.";if($("#set-farm")){$("#set-farm").value=state.farm||"";$("#set-place").value=state.place||"";$("#set-family").value=state.family||"";$("#set-volume").value=state.volume||"volume I";}}
function renderPeople(){var root=$("#people-grid");if(!root)return;root.innerHTML="";var empty=$("#people-empty");if(empty)empty.hidden=state.people.length>0;state.people.forEach(function(p){var card=document.createElement("article");card.className="card";card.innerHTML='<button class="hit" type="button">'+(p.photo?'<img class="portrait" src="'+p.photo+'" alt="">':'')+'<div class="meta"><h3>'+p.name+'</h3><div class="role">'+(p.role||"")+'</div></div></button>';card.querySelector("button").addEventListener("click",function(){openPerson(p);});root.appendChild(card);});}
function openPerson(p){var modal=$("#modal");modal.innerHTML='<div class="modal-card">'+(p.photo?'<img src="'+p.photo+'" alt="">':'')+'<div class="body"><div class="role">'+(p.years||"")+'</div><h3>'+p.name+'</h3><p class="role">'+(p.role||"")+'</p><p>'+(p.bio||"")+'</p><button class="btn" data-del="'+p.id+'" type="button">Tirar do volume</button></div></div>';modal.classList.add("open");var del=modal.querySelector("[data-del]");if(del)del.addEventListener("click",function(){state.people=state.people.filter(function(x){return x.id!==p.id;});persist();modal.classList.remove("open");});}
function renderTree(){var tree=$("#tree");if(!tree)return;if(!state.people.length){tree.innerHTML='<p class="hint">A árvore aparece quando você guarda a primeira pessoa.</p>';return;}tree.innerHTML='<div class="branch-label">Quem entra neste volume</div><div class="generation">'+state.people.map(function(p){return '<button class="person-chip" data-id="'+p.id+'" type="button">'+(p.photo?'<img src="'+p.photo+'" alt="">':'')+'<span>'+p.name.split(" ")[0]+'</span></button>';}).join("")+'</div>';}
function renderTime(){var root=$("#timeline");if(!root)return;if(!state.events.length){root.innerHTML='<p class="hint">Nenhum marco ainda.</p>';return;}root.innerHTML=state.events.slice().sort(function(a,b){return String(a.year).localeCompare(String(b.year));}).map(function(e){return '<article class="event"><div class="year">'+e.year+'</div><h3>'+e.title+'</h3><p>'+(e.text||"")+'</p></article>';}).join("");}
function renderStories(){var root=$("#stories");if(!root)return;if(!state.stories.length){root.innerHTML='<p class="hint">Causo ainda não entrou.</p>';return;}root.innerHTML=state.stories.map(function(s){return '<article class="story"><h3>'+s.title+'</h3><p>'+s.text+'</p><footer>'+[s.by,s.when].filter(Boolean).join(" · ")+'</footer></article>';}).join("");}
function renderAlbums(filter){filter=filter||"Todos";var root=$("#photo-grid");if(!root)return;var photos=state.photos.filter(function(p){return filter==="Todos"||p.album===filter;});var empty=$("#photos-empty");if(empty)empty.hidden=state.photos.length>0;root.innerHTML=photos.map(function(p){return '<article class="card photo-card"><button class="hit" type="button" data-open="'+p.id+'"><img class="thumb" src="'+p.src+'" alt=""><div class="caption"><strong>'+p.title+'</strong><br>'+p.album+' · '+(p.caption||"")+'</div></button><button class="kill" data-kill="'+p.id+'" type="button">×</button></article>';}).join("");root.querySelectorAll("[data-open]").forEach(function(b){b.addEventListener("click",function(){var photo=state.photos.filter(function(x){return x.id===b.dataset.open;})[0];if(photo)openLightbox(photo.src,photo.title+" — "+(photo.caption||""));});});root.querySelectorAll("[data-kill]").forEach(function(b){b.addEventListener("click",function(e){e.stopPropagation();state.photos=state.photos.filter(function(x){return x.id!==b.dataset.kill;});persist();});});}
function openLightbox(src,caption){var box=$("#lightbox");box.innerHTML='<img src="'+src+'" alt=""><p class="caption" style="color:#f3eadc">'+(caption||"")+'</p>';box.classList.add("open");}
function renderAlbumFilters(){var wrap=$("#album-filters");if(!wrap)return;wrap.innerHTML=["Todos"].concat(ALBUMS).map(function(name,i){return '<button class="btn '+(i===0?"primary":"")+'" data-album="'+name+'" type="button">'+name+'</button>';}).join("");wrap.onclick=function(e){var btn=e.target.closest("button");if(!btn)return;wrap.querySelectorAll("button").forEach(function(b){b.classList.toggle("primary",b===btn);});renderAlbums(btn.dataset.album);};}
function persist(){save(state);paint();}
function paint(){renderHouse();renderPeople();renderTree();renderTime();renderStories();renderAlbums();}
function startMine(farm,place,family){state=emptyHouse();state.farm=farm;state.place=place;state.family=family;persist();if($("#setup"))$("#setup").classList.remove("open");go("guardar");toast("Casa aberta. Agora manda a foto da capa.");}
document.addEventListener("DOMContentLoaded",function(){
  renderAlbumFilters();paint();
  if(!state.started&&$("#setup"))$("#setup").classList.add("open");
  document.querySelectorAll("[data-view]").forEach(function(btn){btn.addEventListener("click",function(){go(btn.dataset.view);});});
  if($("#form-setup"))$("#form-setup").addEventListener("submit",function(e){e.preventDefault();startMine($("#boot-farm").value.trim(),$("#boot-place").value.trim(),$("#boot-family").value.trim());});
  if($("#btn-see-demo"))$("#btn-see-demo").addEventListener("click",function(){$("#setup").classList.remove("open");});
  if($("#form-house"))$("#form-house").addEventListener("submit",function(e){e.preventDefault();state.started=true;state.farm=$("#set-farm").value.trim();state.place=$("#set-place").value.trim();state.family=$("#set-family").value.trim();state.volume=$("#set-volume").value.trim()||"volume I";persist();go("capa");toast("Casa salva.");});
  if($("#form-person"))$("#form-person").addEventListener("submit",function(e){e.preventDefault();var file=$("#p-photo").files[0];var goAdd=function(photo){state.people.push({id:uid(),name:$("#p-name").value.trim(),role:$("#p-role").value.trim(),years:$("#p-years").value.trim(),bio:$("#p-bio").value.trim(),photo:photo||""});e.target.reset();persist();go("familia");toast("Pessoa entrou no volume.");};if(file){compressFile(file).then(goAdd);}else{goAdd("");}});
  if($("#form-event"))$("#form-event").addEventListener("submit",function(e){e.preventDefault();state.events.push({year:$("#e-year").value.trim(),title:$("#e-title").value.trim(),text:$("#e-text").value.trim()});e.target.reset();persist();go("tempo");});
  if($("#form-story"))$("#form-story").addEventListener("submit",function(e){e.preventDefault();state.stories.push({title:$("#s-title").value.trim(),text:$("#s-text").value.trim(),by:$("#s-by").value.trim(),when:$("#s-when").value.trim()});e.target.reset();persist();go("causos");});
  if($("#add-photo"))$("#add-photo").addEventListener("submit",function(e){e.preventDefault();var file=$("#photo-file").files[0];var title=$("#photo-title").value.trim();var btn=e.target.querySelector("button[type=submit]");if(!file||!title){toast("Escolhe a foto e põe um título.");return;}if(btn){btn.disabled=true;btn.textContent="Guardando…";}compressFile(file).then(function(src){var album=$("#photo-album").value;var caption=$("#photo-caption").value.trim();state.photos.unshift({id:uid(),src:src,title:title,album:album,caption:caption});if($("#photo-cover")&&$("#photo-cover").checked){state.cover=src;if(album==="A Sede")state.farmPhoto=src;}if(!state.cover)state.cover=src;persist();e.target.reset();toast("Foto entrou no paiol.");go("albuns");}).catch(function(){toast("Essa foto não entrou. Tenta outra.");}).then(function(){if(btn){btn.disabled=false;btn.textContent="Guardar no paiol";}});});
  if($("#btn-start-mine"))$("#btn-start-mine").addEventListener("click",function(){if(!confirm("Apaga o exemplo e começa o seu Volume I?"))return;startMine(($("#set-farm").value||"").trim()||"A fazenda",($("#set-place").value||"").trim(),($("#set-family").value||"").trim());});
  if($("#btn-backup"))$("#btn-backup").addEventListener("click",function(){var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state)],{type:"application/json"}));a.download="paiol-"+(state.farm||"album").replace(/\s+/g,"-").toLowerCase()+".json";a.click();});
  if($("#import-backup"))$("#import-backup").addEventListener("change",function(e){var file=e.target.files[0];if(!file)return;file.text().then(function(t){state=Object.assign(emptyHouse(),JSON.parse(t),{started:true});persist();go("capa");toast("Backup entrou.");}).catch(function(){toast("Esse arquivo não é backup do Paiol.");});});
  if($("#tree"))$("#tree").addEventListener("click",function(e){var chip=e.target.closest("[data-id]");if(!chip)return;var person=state.people.filter(function(p){return p.id===chip.dataset.id;})[0];if(person)openPerson(person);});
  if($("#modal"))$("#modal").addEventListener("click",function(e){if(e.target.id==="modal")e.currentTarget.classList.remove("open");});
  if($("#lightbox"))$("#lightbox").addEventListener("click",function(e){if(e.target.id==="lightbox"||e.target.tagName==="IMG")e.currentTarget.classList.remove("open");});
});
